### PR TITLE
Fix: adding refund method to Gateway

### PR DESCRIPTION
**Pull request by szreka**
I've forgot to push this file in - I'm sorry.

### CODE REVIEW

**Comment by aimeoscom** [comment]
Everything complete now?

**Comment by szreka** [comment]
Yes it is, and I'm sorry again.
It was working fine for me as I had this file changed locally. 
I am able to create a refund the following way:
```
$gateway = \Omnipay\Omnipay::create('Sofort');
$gateway->initialize(array(
    'username' => 'username',
    'password' => 'password',
    'projectId' => 'projectid',
    'testMode' => true
));

$response = $gateway->refund(array(
    'amount' => 10.21,
    'transaction_reference' => '192855-574699-5E4D12A9-DA19',
))->send();
```

Status will be: `accepted`

Transaction info in Sofort:
Screenshot 2020-02-19 at 17 07 24

I double checked, everything pushed in, and using current code.

**Comment by szreka** [comment]
Thank you!

**Comment by aimeoscom** [comment]
Great! New 3.1.0 release is tagged now

**Comment by danslo** [comment]
@aimeoscom 

Thanks for your speedy responses above, it's much appreciated.

I just wanted to let you know that this repo is not auto updating on packagist, so the new tag hasn't arrived there yet.

We're working around it by adding this repo in root composer.json, but you may want to set up hooks.

Thanks again!

**Comment by aimeoscom** [comment]
Thanks for the hint, the problem is fixed now

**Pull request merged**
