### PR TITLE
Adding refund

### PR DESCRIPTION
**Pull request by szreka**

### CODE REVIEW

**Comment by aimeos** [comment]
Thanks a lot for your PR! :-)

Can you please fix that minor coding style issue that prevents test succeed?
https://travis-ci.org/aimeoscom/omnipay-sofort/jobs/652548116?utm_medium=notification&utm_source=github_status

**Comment by szreka** [comment]
Sure thing, I just did. My intention was to create the PR first to the forked repo, but oh well, long day.
Thanks for your quick reply!

**Comment by aimeoscom** [comment]
Can you check again that it works? Then, we can tag a new release.

**Comment by szreka** [comment]
```
$gateway = \Omnipay\Omnipay::create('Sofort');
$gateway->initialize(array(
    'username' => '192855',
    'password' => 'c5e22941d26465170e9fc93a3af11d64',
    'projectId' => '574699',
    'testMode' => true
));

$response = $gateway->refund(array(
    'amount' => 9.99,
    'transaction_reference' => '192855-574699-5E4D30D5-85CB',
))->send();

$transactionReference = $response->getTransactionReference();

var_dump($transactionReference);
```
Transaction reference: `"192855-574699-5E4D30D5-85CB"`

Result in Sofort:
Screenshot 2020-02-19 at 16 34 53

**Comment by szreka** [comment]
```
$gateway = \Omnipay\Omnipay::create('Sofort');
$gateway->initialize(array(
    'username' => 'our_id',
    'password' => 'our_password',
    'projectId' => 'project_id',
    'testMode' => true
));

$response = $gateway->refund(array(
    'amount' => 9.99,
    'transaction_reference' => '192855-574699-5E4D30D5-85CB',
))->send();

$transactionReference = $response->getTransactionReference();

var_dump($transactionReference);
```
Transaction reference: `"192855-574699-5E4D30D5-85CB"`

Result in Sofort:
Screenshot 2020-02-19 at 16 34 53

**Comment by szreka** [comment]
AH WAIT! I missed something. Going to add it quickly. I'm terribly sorry.

**Pull request merged**
